### ISSUE TITLE
First Oddy Spike BYU confirmed

### ISSUE THREAD

**Issue by KasiKarra** [LLNL-Collaboration/BYU_Alkemi_2017#1]
Confirmed Oddy Spike for Run 0, Cycle 6899, Zone 10806

**Comment by KasiKarra** [comment]
Code 
if __name__ == '__main__':
    if len(sys.argv) < 3:
        print 'Usage: FeatureDataReader.py dataDir numParts'
        sys.exit(1)

    np.set_printoptions(suppress=True, precision=4)

    reader = FeatureDataReader(sys.argv[1], int(sys.argv[2]))
    (run, part, cycle, zone) = (0, 0, 6899, 10806)

    data = reader.getMetricNames()
    print data

    data = reader.readZone(run, cycle, zone)
    print data

    data = reader.readAllZonesInCycle(run, cycle)
    j = data.shape[0]
    i=0
    OddyFile1 = open("OddyFile1.csv","w")

	
    while i < j:
    	OddyFile1.write(str(data[i][6])  + ",\n")
        i = i+1

**Comment by mjoehler94** [comment]
Here is the plot we made of the oddy spike for the first failed zone. 

![image](https://cloud.githubusercontent.com/assets/19435987/22479568/6f79e90c-e7ab-11e6-9a88-18aafd98c540.png)

**Comment by minglars** [comment]
Looks good!
